import config from '@payload-config'
import { getPayload, type Payload, type RequiredDataFromCollectionSlug } from 'payload'

import type { Author, User } from '@/payload-types'

// One-shot migration for databases seeded before `Posts.authors` was repointed
// from `users` to the new public `authors` collection. It creates an Author for
// every referenced user and rewrites each post's `authors` array to the new IDs.
// Idempotent: authors are matched by name, so re-running reuses existing docs.
// No users / no posts → the script simply does nothing.

const authorNameOf = (user: User) => {
  if (user.name) return user.name
  if (user.email) return user.email.split('@')[0]
  return null
}

const findAuthorByName = async (payload: Payload, name: string) => {
  const existing = await payload.find({
    collection: 'authors',
    limit: 1,
    where: { name: { equals: name } },
  })

  return (existing.docs[0] as Author) || null
}

const ensureAuthorForUser = async (payload: Payload, user: User) => {
  const name = authorNameOf(user)

  if (!name) {
    payload.logger.warn(`User ${user.id} has no name/email — skipped`)
    return null
  }

  const existing = await findAuthorByName(payload, name)

  if (existing) {
    payload.logger.info(`Author "${name}" already exists — reused`)
    return existing
  }

  // `slug` is auto-generated by the collection's beforeChange hook, but its
  // field is typed `required`, so we assert the create data shape here.
  const created = await payload.create({
    collection: 'authors',
    context: { disableRevalidate: true },
    data: { name } as RequiredDataFromCollectionSlug<'authors'>,
  })

  payload.logger.info(`Created author "${name}"`)

  return created as Author
}

const toAuthorId = (author: Author | string) =>
  typeof author === 'object' ? String(author.id) : String(author)

const buildUserToAuthorMap = async (payload: Payload) => {
  const users = await payload.find({ collection: 'users', depth: 0, limit: 1000, pagination: false })

  const entries = await Promise.all(
    users.docs.map(async (user) => {
      const author = await ensureAuthorForUser(payload, user)
      return author ? ([String(user.id), String(author.id)] as const) : null
    }),
  )

  return new Map(entries.filter(Boolean) as (readonly [string, string])[])
}

const relinkPosts = async (payload: Payload, userToAuthor: Map<string, string>) => {
  const posts = await payload.find({
    collection: 'posts',
    depth: 0,
    limit: 1000,
    pagination: false,
    select: { authors: true },
  })

  const remapAuthor = (author: Author | string) => userToAuthor.get(toAuthorId(author))

  const relinkOne = async (post: (typeof posts.docs)[number]) => {
    const oldAuthors = post.authors || []

    if (oldAuthors.length === 0) return

    const newAuthorIds = oldAuthors.map(remapAuthor).filter(Boolean) as string[]

    // Nothing mapped → post already references authors, not users. Leave it.
    if (newAuthorIds.length === 0) return

    await payload.update({
      collection: 'posts',
      context: { disableRevalidate: true },
      data: { authors: newAuthorIds },
      id: post.id,
    })

    payload.logger.info(`Relinked post ${post.id} → ${newAuthorIds.length} author(s)`)
  }

  await Promise.all(posts.docs.map(relinkOne))
}

const migrateAuthors = async () => {
  const payload = await getPayload({ config })

  const userToAuthor = await buildUserToAuthorMap(payload)

  if (userToAuthor.size === 0) {
    payload.logger.info('No users to migrate — nothing to do')
    return
  }

  await relinkPosts(payload, userToAuthor)
  payload.logger.info('Author migration complete')
}

await migrateAuthors()
process.exit(0)
